### ISSUE TITLE
Wrong getter for ID property

### ISSUE THREAD

**Issue by turbokuzmich** [joshdholtz/jsonapi-ios#17] opened 2015-07-16 09:59 UTC
Found several places where resource ID property is referenced this way:
```objc
resource.ID
```
Suppose that the correct way would be:
```objc
JSONAPIResourceDescriptor *desc = <get resource descriptor somehow>;
...
[[resource valueForKey:desc.idProperty] blah];
```

**Comment by joshdholtz** [comment] 2015-10-14 17:57
@turbokuzmich I don't think I follow what the issue is 100% :innocent: Would you be able to give a different example?

**Comment by joshdholtz** [comment] 2015-10-14 18:06
Or link to specific places?

**Comment by joshdholtz** [comment] 2015-12-21 15:07
No more info so closing

**Closed by joshdholtz** 2015-12-21 15:07 UTC
